version: "3.9"
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: quanticx
      POSTGRES_USER: quanticx
      POSTGRES_PASSWORD: quanticx
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7
    ports:
      - "6379:6379"
  backend:
    build: ../
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload
    working_dir: /app
    environment:
      DATABASE_URL: postgresql+asyncpg://quanticx:quanticx@postgres:5432/quanticx
      REDIS_URL: redis://redis:6379/0
      ENV: docker
    volumes:
      - ../:/app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
  bot:
    build: ../
    command: python bot/main.py
    working_dir: /app
    environment:
      REDIS_URL: redis://redis:6379/0
    volumes:
      - ../:/app
    depends_on:
      - redis
  worker:
    build: ../
    command: celery -A backend.celery_app:app worker -l info
    working_dir: /app
    environment:
      REDIS_URL: redis://redis:6379/0
      DATABASE_URL: postgresql+asyncpg://quanticx:quanticx@postgres:5432/quanticx
    volumes:
      - ../:/app
    depends_on:
      - redis
      - postgres
volumes:
  pgdata:
